# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true



# Mod Properties
mod_name = Configured
mod_id = configured
mod_version=1.9.8
maven_group=configured
archives_base_name=Configured

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT


# Dependencies
betterconfig_version = 2.7.0
fabric_api_version=0.154.0+26.2