name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Call build
        uses: ./.github/workflows/build.yml
        with:
          release: true

      - name: Upload hash
        run: |
            cd "build/libs" || continue
            for f in *; do
              sha256sum "$f" > "$f.sha256"
              gh release upload "${{ github.event.release.tag_name }}" "$f" "$f.sha256" --clobber
            done
            cd - >/dev/null
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
